homepage:
    path: /
    defaults: { _controller: BlogBundle:Blog:homepage }

blog_teaser:
    path: /teaser
    defaults: { _controller: BlogBundle:Blog:teaser }

blog_view:
    path: /blog/{id}
    defaults: { _controller: BlogBundle:Blog:blogView }
    requirements:
      id: \d+

blog_about_us:
    path: /about_us
    defaults: { _controller: BlogBundle:Blog:aboutAs }

show:
    path: /show
    defaults: { _controller: BlogBundle:Page:show }

admin:
    path: /admin
    defaults: { _controller: BlogBundle:Admin:admin }